import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";

// --- ESTILOS ---
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "./styles/global.css";

// --- FONTAWESOME ---
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

// Iconos Sólidos (fas)
import {
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBan,
  faBed,
  faBell,
  faBellSlash,
  faBinoculars,
  faBroom,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faCalendarMinus,
  faCalendarXmark,
  faCamera,
  faCar,
  faChartLine,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faCloudArrowUp,
  faCompass,
  faDoorOpen,
  faDroplet,
  faEarthAmericas,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFan,
  faFilter,
  faFilePdf,
  faGripVertical,
  faHandHoldingDollar,
  faHandsHolding,
  faHandshakeAngle,
  faHeart,
  faHeartPulse,
  faHotel,
  faHouseChimney,
  faHotTubPerson,
  faIdCard,
  faImages,
  faKey,
  faLeaf,
  faLock,
  faLocationDot,
  faMagnifyingGlass,
  faMartiniGlass,
  faMoon,
  faMound,
  faMountainSun,
  faPaperPlane,
  faPersonPraying,
  faPhone,
  faPlane,
  faPlus,
  faReceipt,
  faRightFromBracket,
  faRightToBracket,
  faRotate,
  faRotateLeft,
  faSave,
  faSeedling,
  faShareNodes,
  faShieldHalved,
  faSignOutAlt,
  faSnowflake,
  faStar,
  faSun,
  faTableCellsLarge,
  faTag,
  faTimesCircle,
  faTrash,
  faTrashCan,
  faTree,
  faTv,
  faUser,
  faUserCircle,
  faUserGear,
  faUserPen,
  faUserPlus,
  faUserShield,
  faUsers,
  faWifi,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

// Iconos de Marcas (fab)
import {
  faInstagram,
  faFacebook,
  faTiktok,
  faWhatsapp,
  faFacebookF,
} from "@fortawesome/free-brands-svg-icons";

// Iconos Regulares (far) - AQUÍ ESTÁ EL LÁPIZ DELGADO
import { faPenToSquare } from "@fortawesome/free-regular-svg-icons";

// Añadir todos los iconos a la librería de una sola vez
library.add(
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBan,
  faBed,
  faBell,
  faBellSlash,
  faBinoculars,
  faBroom,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faCalendarMinus,
  faCalendarXmark,
  faCamera,
  faCar,
  faChartLine,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faCloudArrowUp,
  faCompass,
  faDoorOpen,
  faDroplet,
  faEarthAmericas,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFan,
  faFilter,
  faFilePdf,
  faGripVertical,
  faHandHoldingDollar,
  faHandsHolding,
  faHandshakeAngle,
  faHeart,
  faHeartPulse,
  faHotel,
  faHouseChimney,
  faHotTubPerson,
  faIdCard,
  faImages,
  faKey,
  faLeaf,
  faLock,
  faLocationDot,
  faMagnifyingGlass,
  faMartiniGlass,
  faMoon,
  faMound,
  faMountainSun,
  faPaperPlane,
  faPenToSquare,
  faPersonPraying,
  faPhone,
  faPlane,
  faPlus,
  faReceipt,
  faRightFromBracket,
  faRightToBracket,
  faRotate,
  faRotateLeft,
  faSave,
  faSeedling,
  faShareNodes,
  faShieldHalved,
  faSignOutAlt,
  faSnowflake,
  faStar,
  faSun,
  faTableCellsLarge,
  faTag,
  faTimesCircle,
  faTrash,
  faTrashCan,
  faTree,
  faTv,
  faUser,
  faUserCircle,
  faUserGear,
  faUserPen,
  faUserPlus,
  faUserShield,
  faUsers,
  faWifi,
  faXmark,
  faFacebook,
  faFacebookF,
  faInstagram,
  faTiktok,
  faWhatsapp
);

// --- CREAR LA APP ---
const app = createApp(App);

app.use(createPinia());
app.use(router);

// Registrar el componente globalmente
app.component("font-awesome-icon", FontAwesomeIcon);

app.mount("#app");
